---
title: "Ukraine"
author: "Daniel Shapiro"
date: "4/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=999)
library(tidyverse)
library(readr)
library(readxl)
library(cowplot)
library(stargazer)
library(gridExtra)
```

```{r}
Totals <- read_xlsx("Totals.xlsx")
```

```{r pct graph}

# Get percentages

pct <- Totals %>%
  mutate(`No Mask` = `No Mask`/`Total` * 100) %>%
  mutate(`Mask Covers Nothing` = `Mask Covers Nothing`/`Total` * 100) %>%
  mutate(`Mask Covers Mouth` = `Mask Covers Mouth`/`Total` * 100) %>%
  mutate(`Full Mask` = `Full Mask`/`Total` * 100)

pct <- pivot_longer(pct, cols = c(`No Mask`, `Mask Covers Nothing`, `Mask Covers Mouth`, `Full Mask`)) %>%
  rename(Percentage = value) %>%
  rename(`Level of Adherence` = name)

region <- ggplot(pct, aes(x = Region, y = Percentage, fill = `Level of Adherence`)) +
  geom_col() +
  coord_flip() +
  scale_fill_manual(values = c("light green", "yellow", "orange", "red")) +
  labs(title = "Mask Wearing By Region")

region

ggsave("region.png")
```

```{r hdi}
City <- read_xlsx("City Data.xlsx")
```

```{r hdireal}
City2 <- City %>%

# Filter to get only full mask
  
  filter(Category == "Full Mask") %>%

# Multiply HDI by 100 and Total Ukr Cases for readability and interpretation purposes
  
  mutate(`2019 Oblast HDI` = `2019 Oblast HDI` * 100) %>%
  mutate(`Total Ukr Cases` = `Total Ukr Cases` / 1000)
```

```{r regression, results = 'asis'}
hdireg <- lm(Percentage ~ `2019 Oblast HDI` + `Total Ukr Cases` + `Not Oblast Center` + `2001 Pct Russian` + `Precinct Pct Zelensky`, data = City2)

summary(hdireg)

stargazer(hdireg, title = "Impact of City-Specific Factors on Percent Full Mask Wearing", type = "html")
```

```{r graphs, warning = FALSE}
City3 <- City %>%
  filter(Category == "Full Mask")

plot1 <- ggplot(City3, aes(x = `2019 Oblast HDI`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .4, vjust = -1.1), size = 3) +
  labs(title = "Relationship Between Oblast HDI and Percent Full Masking",
       subtitle = "Point Size is Relative to City Size") +
  theme(legend.position = "none")

plot1

plot2 <- ggplot(City3, aes(x = `Total Ukr Cases`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .5, vjust = -1.1), size = 3) +
  labs(title = "Relationship Between Total Ukrainian Cases and Percent Full Masking",
       subtitle = "Point Size is Relative to City Size") +
  theme(legend.position = "none") 

plot2

plot3 <- ggplot(City3, aes(x = `2001 Pct Russian`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .45, vjust = -1), size = 3) +
  labs(title = "Relationship Between Pct. of Native Russian Speakers and Pct. Full Masking",
       subtitle = "Point Size is Relative to City Size, Data is From 2001") +
  theme(legend.position = "none")

plot3

plot4 <- ggplot(City3, aes(x = `Precinct Pct Zelensky`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .58, vjust = -1), size = 3) +
  labs(title = "Relationship Between Pct. Voting for Zelensky and Pct. Full Masking",
       subtitle = "Point Size is Relative to City Size",
       x = "Precinct Percentage for Zelensky",
       y = "Percentage Full Masking") +
  theme(legend.position = "none")

plot4

plot5 <- ggplot(City3, aes(x = `Precinct Pct Boyko`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .45, vjust = -1), size = 3) +
  labs(title = "Relationship Between Pct. Voting for Boyko and Pct. Full Masking",
       subtitle = "Point Size is Relative to City Size") +
  theme(legend.position = "none")

plot5

plot6 <- ggplot(City3, aes(x = `Precinct Pct Poroshenko`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .45, vjust = -1), size = 3) +
  labs(title = "Relationship Between Pct. Voting for Poroshenko and Pct. Full Masking",
       subtitle = "Point Size is Relative to City Size") +
  theme(legend.position = "none")

plot6

ggsave(plot = plot1, filename = "hdi.png")
ggsave(plot = plot2, filename = "cases.png")
ggsave(plot = plot3, filename = "russ.png")
ggsave(plot = plot4, filename = "zelensky.png")
ggsave(plot = plot5, filename = "boyko.png")
ggsave(plot = plot6, filename = "poroshenko.png")
```

```{r city size}
City4 <- read_xlsx("City Size Condensed.xlsx")

plot7 <- ggplot(City4, aes(x = Size, y = Percentage)) +
  geom_col(fill = 'blue', width = 0.5) +
  labs(title = "Relationship Between City Size and Percent Full Masking") +
  geom_text(aes(x = Size, y = Percentage, label = Percentage), stat = "sum", vjust = -0.5, size = 4)

plot7

ggsave(plot = plot7, filename = "size.png")
```

```{r stores}
stores <- read_xlsx("Supermarkets.xlsx")
```

```{r}
ggplot(stores, aes(x = Category, y = Value, fill = `Grocery Store`)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("blue", "orange")) +
  labs(title = "Mask Wearing Tendencies by Grocery Store")

ggsave("supermarkets.png")
```

```{r cases w/o South}
City5 <- City3 %>%
  filter(Region != "South")

ggplot(City5, aes(x = `Total Ukr Cases`, y = Percentage)) +
  geom_point(aes(size = `2020 City Population`)) +
  geom_smooth(method = "lm", se = TRUE) +
  geom_text(aes(label = City, hjust = .5, vjust = -1.1), size = 3) +
  labs(title = "Relationship Between Total Ukrainian Cases and Percent Full Masking",
       subtitle = "Southern Cities Removed; Point Size is Relative to City Size") +
  theme(legend.position = "none") 
```

